stages:
  gr-book-ids:
    cmd: python ../run.py export-goodreads --book-ids
    deps:
    - ../index/gr-index-books.status
    - ../scripts/export-goodreads.py
    outs:
    - gr-book-ids.csv.gz
    - gr-book-ids.parquet
  gr-work-ratings:
    cmd: python ../run.py export-goodreads --work-ratings
    deps:
    - ../index/gr-index-ratings.status
    - ../scripts/export-goodreads.py
    outs:
    - gr-work-ratings.parquet
  gr-work-actions:
    cmd: python ../run.py export-goodreads --work-actions
    deps:
    - ../index/gr-index-ratings.status
    - ../scripts/export-goodreads.py
    outs:
    - gr-work-actions.parquet
  gr-work-titles:
    cmd: python ../run.py export-goodreads --work-titles
    deps:
    - ../index/gr-book-info.status
    - ../scripts/export-goodreads.py
    outs:
    - gr-work-titles.parquet
    - gr-work-titles.csv.gz
  gr-work-authors:
    cmd: python ../run.py export-goodreads --work-authors
    deps:
    - ../index/gr-book-info.status
    - ../scripts/export-goodreads.py
    outs:
    - gr-work-authors.parquet
    - gr-work-authors.csv.gz
  gr-work-genres:
    cmd: python ../run.py export-goodreads --work-genres
    deps:
    - ../index/gr-book-info.status
    - ../scripts/export-goodreads.py
    outs:
    - gr-work-genres.parquet
    - gr-work-genres.csv.gz
