stages:
  gr-book-ids:
    cmd: python ../run.py export-goodreads --book-ids
    deps:
    - ../index/gr-index-books.status
    - ../scripts/export-goodreads.py
    outs:
    - gr-book-ids.csv.gz
    - gr-book-ids.parquet
  gr-work-ratings:
    cmd: python ../run.py export-goodreads --work-ratings
    deps:
    - ../index/gr-index-ratings.status
    - ../scripts/export-goodreads.py
    outs:
    - gr-work-ratings.parquet
