stages:
  clean-ratings:
    cmd: python ../run.py bx-extract.py ../data/BX-CSV-Dump.zip cleaned-ratings.csv
    deps:
    - bx-extract.py
    - ../data/BX-CSV-Dump.zip
    outs:
    - cleaned-ratings.csv

  cluster-ratings:
    cmd: python run.py bx-cluster-ratings.py
    deps:
    - bx-cluster-ratings.py
    - cleaned-ratings.csv
    - ../book-links/isbn-clusters.parquet
    outs:
    - bx-cluster-ratings.parquet

  cluster-actions:
    cmd: python run.py bx-cluster-actions.py
    deps:
    - bx-cluster-actions.py
    - cleaned-ratings.csv
    - ../book-links/isbn-clusters.parquet
    outs:
    - bx-cluster-actions.parquet

  schema:
    foreach:
    - bx-cluster-actions
    - bx-cluster-ratings
    do:
      cmd: python ../run.py --rust pq-info -o ${item}.json ${item}.parquet
      deps:
      - ${item}.parquet
      outs:
      - ${item}.json:
          cache: false
