stages:
  clean-ratings:
    cmd: python ../run.py bx-extract ../data/BX-CSV-Dump.zip cleaned-ratings.csv
    deps:
    - ../scripts/bx-extract.py
    - ../data/BX-CSV-Dump.zip
    outs:
    - cleaned-ratings.csv

  bx-cluster-ratings:
    cmd: python ../run.py --rust fusion bx-cluster-ratings.tcl
    deps:
    - bx-cluster-ratings.tcl
    - cleaned-ratings.csv
    - ../book-links/all-isbns.parquet
    - ../book-links/isbn-clusters.parquet
    outs:
    - bx-cluster-ratings.csv.gz

  bx-cluster-actions:
    cmd: python ../run.py --rust fusion bx-cluster-actions.tcl
    deps:
    - bx-cluster-actions.tcl
    - cleaned-ratings.csv
    - ../book-links/all-isbns.parquet
    - ../book-links/isbn-clusters.parquet
    outs:
    - bx-cluster-actions.csv.gz
