stages:
  clean-ratings:
    cmd: cargo run --release -- bx extract ../data/BX-CSV-Dump.zip cleaned-ratings.csv
    deps:
      - "../src/cli/bx"
      - "../data/BX-CSV-Dump.zip"
    outs:
      - cleaned-ratings.csv
  cluster-ratings:
    cmd: cargo run --release -- bx cluster-actions --ratings -o bx-cluster-ratings.parquet
    deps:
      - "../src/cli/bx"
      - cleaned-ratings.csv
      - "../book-links/isbn-clusters.parquet"
    outs:
      - bx-cluster-ratings.parquet
  cluster-actions:
    cmd: cargo run --release -- bx cluster-actions --add-actions -o bx-cluster-actions.parquet
    deps:
      - "../src/cli/bx"
      - cleaned-ratings.csv
      - "../book-links/isbn-clusters.parquet"
    outs:
      - bx-cluster-actions.parquet