stages:
  clean-ratings:
    cmd: python ../run.py bx-extract ../data/BX-CSV-Dump.zip cleaned-ratings.csv
    deps:
    - ../scripts/bx-extract.py
    - ../data/BX-CSV-Dump.zip
    outs:
    - cleaned-ratings.csv

  cluster-ratings:
    cmd: python run.py --rust cluster-actions -s bx-ratings -o bx/bx-cluster-ratings.parquet
    wdir: ..
    deps:
    - src/bin/cluster-actions/
    - bx/cleaned-ratings.csv
    - book-links/isbn-clusters.parquet
    outs:
    - bx/bx-cluster-ratings.parquet

  cluster-actions:
    cmd: python run.py --rust cluster-actions -s bx-actions -o bx/bx-cluster-actions.parquet
    wdir: ..
    deps:
    - src/bin/cluster-actions/
    - bx/cleaned-ratings.csv
    - book-links/isbn-clusters.parquet
    outs:
    - bx/bx-cluster-actions.parquet
