stages:
  clean-ratings:
    cmd: python ../run.py bx-extract ../data/BX-CSV-Dump.zip cleaned-ratings.csv
    deps:
    - ../scripts/bx-extract.py
    - ../data/BX-CSV-Dump.zip
    outs:
    - cleaned-ratings.csv
