goodreads:
  # Switch which GoodReads data files are used.  The simple files are
  # publicly downloadable. If you have a copy of the full inteaction
  # data, change this to "full" to use that data.
  interactions: simple
