# Control which BookCrossing and Amazon data sets are enabled
bx:
  # BX is disabled by default since the source site is offline
  enabled: false

az2014:
  enabled: true

az2018:
  enabled: true
  # configure the input source. can be "ratings" or "reviews".
  from: ratings

# Configure the GoodReads data
goodreads:
  # Enable or disable GoodReads.  Disabling GoodReads removes its use
  # entirely, not only for interactions.
  enabled: true

  # Control whether to incorporate book ratings or just interactions.  The
  # review files are available upon request from the UCSD team.
  reviews: false

openlibrary:
  # Date of the OpenLibrary to download
  # you can find available dumps at https://archive.org/details/ol_exports?sort=-publicdate
  date: "2023-10-31"

viaf:
  # get a current url from https://viaf.org/viaf/data/
  # unlike openlibrary, old links don't work
  url: https://viaf.org/viaf/data/viaf-20231107-clusters-marc21.xml.gz
