# Control which BookCrossing and Amazon data sets are enabled
bx:
  enabled: true

az2014:
  enabled: true

az2018:
  enabled: true

# Configure the GoodReads data
goodreads:
  # Enable or disable GoodReads.  Disabling GoodReads removes its use
  # entirely, not only for interactions.
  enabled: true
  # Switch which GoodReads interaction data files are used.  The simple
  # files are the publicly-downloadable CSVs. Full interaction data in
  # JSON is available upon request from the UCSD team; if you have a
  # copy, change this to `full` to use it.
  interactions: simple
