dependencies:
- flake8
- conda-lock =1
# we need tcllib to re-render the pipeline, but it's only on x86 for now
- tcllib # [linux64]
- tcllib # [win64]
- tcllib # [osx64]
- jupyterlab >=3.1
- sphinx-autobuild
- seaborn >=0.11
category: dev
