stages:
  ClusterStats:
    cmd: jupytext --to ipynb --execute ClusterStats.py
    deps:
    - ClusterStats.py
    - book-links/cluster-stats.parquet
    outs:
    - ClusterStats.ipynb:
        cache: false
  LinkageStats:
    cmd: jupytext --to ipynb --execute LinkageStats.py
    deps:
    - LinkageStats.py
    - book-links/gender-stats.csv
    outs:
    - LinkageStats.ipynb:
        cache: false
    metrics:
    - book-coverage.json
