stages:
  LinkageStats:
    cmd: jupytext --to ipynb --execute LinkageStats.py
    deps:
    - LinkageStats.py
    - book-links/gender-stats.csv
    outs:
    - LinkageStats.ipynb:
        cache: false
    metrics:
    - book-coverage.json