---
stages:
  ClusterStats:
    cmd: jupytext --to ipynb --execute ClusterStats.py
    deps:
      - ClusterStats.py
      - book-links/cluster-stats.parquet
    outs:
      -
        ClusterStats.ipynb:
          cache: false
  LinkageStats:
    cmd: jupytext --to ipynb --execute LinkageStats.py
    deps:
      - LinkageStats.py
      - book-links/gender-stats.csv
    outs:
      -
        LinkageStats.ipynb:
          cache: false
    metrics:
      - book-coverage.json
  html-report:
    foreach:
      - LinkageStats
      - ClusterStats
    do:
      cmd: jupyter nbconvert --to html "${item}.ipynb"
      deps:
        - ${item}.ipynb
      outs:
        - ${item}.html
  schema:
    foreach:
      - bx/bx-cluster-actions
      - bx/bx-cluster-ratings
      - loc-mds/book-authors
      - loc-mds/book-fields
      - loc-mds/book-ids
      - loc-mds/book-isbn-ids
      - loc-mds/book-isbns
      - loc-mds/name-fields
      - openlibrary/all-authors
      - openlibrary/all-works
      - openlibrary/author-ids-after-works
      - openlibrary/author-names
      - openlibrary/authors
      - openlibrary/edition-authors
      - openlibrary/edition-isbn-ids
      - openlibrary/edition-isbns
      - openlibrary/edition-subjects
      - openlibrary/edition-works
      - openlibrary/editions
      - openlibrary/work-authors
      - openlibrary/work-clusters
      - openlibrary/work-subjects
      - openlibrary/works
      - viaf/author-genders
      - viaf/author-name-index
      - viaf/viaf
    do:
      cmd: python run.py --rust pq-info -o ${item}.json ${item}.parquet
      deps:
        - ${item}.parquet
      outs:
        -
          ${item}.json:
            cache: false

