stages:
  schema:
    cmd: 'true'
    deps:
    - schemas/common-schema.status
    - schemas/loc-mds-schema.status
    - schemas/ol-schema.status
    - schemas/az-schema.status
    - schemas/bx-schema.status
    - schemas/gr-schema.status
    - schemas/viaf-schema.status

  all:
    cmd: 'true'
    deps:
    - index/loc-mds-book-info.status
    - index/gr-book-info.status
    - integrate/author-info.status
    - integrate/author-stats.status
    - integrate/cluster-stats.status
    - index/loc-mds-index-names.status

  LinkageStats:
    cmd: jupytext --to ipynb --execute LinkageStats.py
    deps:
    - LinkageStats.py
    - book-links/gender-stats.csv
    outs:
    - LinkageStats.ipynb:
        cache: false
