---
stages:
  ClusterStats:
    cmd: quarto render ClusterStats.qmd
    deps:
      - ClusterStats.qmd
      - book-links/cluster-stats.parquet
    outs:
      -
        ClusterStats.ipynb:
          cache: false
      - ClusterStats.html
      - ClusterStats_files
  LinkageStats:
    cmd: quarto render LinkageStats.qmd
    deps:
      - LinkageStats.qmd
      - book-links/gender-stats.csv
    outs:
      -
        LinkageStats.ipynb:
          cache: false
      - LinkageStats.html
      - LinkageStats_files
    metrics:
      - book-coverage.json
  schema:
    foreach:
      - az2014/az-cluster-ratings
      - az2014/az-cluster-ratings-5core
      - az2014/ratings
      - az2018/az-cluster-ratings
      - az2018/az-cluster-ratings-5core
      - az2018/ratings
      - book-links/all-isbns
      - book-links/cluster-first-authors
      - book-links/cluster-genders
      - book-links/cluster-graph-edges
      - book-links/cluster-graph-nodes
      - book-links/cluster-hashes
      - book-links/cluster-loc-first-authors
      - book-links/cluster-ol-first-authors
      - book-links/cluster-stats
      - book-links/isbn-clusters
      - bx/bx-cluster-actions
      - bx/bx-cluster-ratings
      - goodreads/book-isbn-ids
      - goodreads/gr-author-info
      - goodreads/gr-book-authors
      - goodreads/gr-book-genres
      - goodreads/gr-book-ids
      - goodreads/gr-book-info
      - goodreads/gr-book-link
      - goodreads/gr-book-series
      - goodreads/gr-cluster-actions
      - goodreads/gr-cluster-actions-5core
      - goodreads/gr-cluster-ratings
      - goodreads/gr-cluster-ratings-5core
      - goodreads/gr-genres
      - goodreads/gr-interactions
      - goodreads/gr-work-actions
      - goodreads/gr-work-actions-5core
      - goodreads/gr-work-gender
      - goodreads/gr-work-info
      - goodreads/gr-work-ratings
      - goodreads/gr-work-ratings-5core
      - loc-mds/book-authors
      - loc-mds/book-fields
      - loc-mds/book-ids
      - loc-mds/book-isbn-ids
      - loc-mds/book-isbns
      - loc-mds/name-fields
      - openlibrary/all-authors
      - openlibrary/all-works
      - openlibrary/author-ids-after-works
      - openlibrary/author-names
      - openlibrary/authors
      - openlibrary/edition-authors
      - openlibrary/edition-isbn-ids
      - openlibrary/edition-isbns
      - openlibrary/edition-subjects
      - openlibrary/edition-works
      - openlibrary/editions
      - openlibrary/work-authors
      - openlibrary/work-clusters
      - openlibrary/work-subjects
      - openlibrary/works
      - viaf/author-genders
      - viaf/author-name-index
      - viaf/viaf
    do:
      cmd: |-
        cargo run --release -- pq-info -o ${item}.json ${item}.parquet
      deps:
        - ${item}.parquet
      outs:
        -
          ${item}.json:
            cache: false

