[project]
authors = ["Michael Ekstrand <mdekstrand@drexel.edu>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "bookdata"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "~=3.12.0"
pandas = "~=2.0"
pyarrow = ">=14"
polars = "~=1.17.0"
python-duckdb = "~=1.1"
duckdb-cli = "~=1.1"
matplotlib = "*"
seaborn = "*"
notebook = ">=6.4"
seedbank = "*"
weasyprint = "*"
curl = "*"
jsonnet = "*"
pyyaml = "*"
docopt-ng = ">=0.9"
rust = "~=1.74"
c-compiler = "*"
cmake = "*"
# using R for analysis
r-tidyverse = "~=2.0"
r-arrow = "*"
r-rmarkdown = "*"
r-jsonlite = "*"
r-irkernel = "*"
r-languageserver = "*"
aria2 = ">=1.37.0,<2"

# dependencies just for working with the data
[feature.data.dependencies]
libsqlite = "=3.48"
dvc = "~=3.30"
dvc-s3 = "~=3.0"
dvc-webdav = "~=3.0"

[feature.dev.dependencies]
ruff = ">=0.4"
rust-src = "~=1.73"
ipython = ">=8"
deno = "~=1.46"
parquet-tools = "*"
visidata = "*"
jupyter_console = ">=6.6.3,<7"

[feature.site.dependencies]
quarto = "~=1.3"
perl = "~=5.32"

[feature.rustdoc]
channels = ["conda-forge/label/rust_dev"]
channel-priority = "disabled"

[feature.rustdoc.dependencies]
rust = { version = ">=1.74", channel = "conda-forge/label/rust_dev" }

[environments]
default = { features = ["site", "data"], solve-group = "default" }
data = { features = ["data"], no-default-feature = true }
dev = { features = ["dev", "data", "site"], solve-group = "default" }
site = { features = ["site", "rustdoc"], no-default-feature = true }
