[project]
authors = ["Michael Ekstrand <mdekstrand@drexel.edu>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "bookdata"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "~=3.12.0"
pandas = "~=2.0"
pyarrow = ">=14"
polars = "~=0.20.0"
matplotlib = "*"
seaborn = "*"
notebook = ">=6.4"
seedbank = "*"
weasyprint = "*"
curl = "*"
jsonnet = "*"
pyyaml = "*"
docopt = "*"
dvc = "~=3.30"
dvc-s3 = "~=3.0"
dvc-webdav = "~=3.0"
rust = "~=1.74"
c-compiler = "*"
cmake = "*"
# using R for analysis
r-tidyverse = "~=2.0"
r-arrow = "*"
r-rmarkdown = "*"
r-jsonlite = "*"
r-irkernel = "*"
r-languageserver = "*"

[feature.dev.dependencies]
ruff = ">=0.4"
rust-src = "~=1.73"
ipython = ">=8"
parquet-tools = "*"
visidata = "*"

[feature.site.dependencies]
rust = "~=1.74"
quarto = "~=1.3"
perl = "~=5.32"

[environments]
default = { features = ["site"], solve-group = "default" }
dev = { features = ["dev", "site"], solve-group = "default" }
site = { features = ["site"], no-default-feature = true }
