[project]
authors = ["Michael Ekstrand <mdekstrand@drexel.edu>"]
channels = ["https://prefix.dev/lenskit-dev", "conda-forge"]
description = "Add a short description here"
name = "bookdata"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]
repro-all = "dvc repro -P"

[dependencies]
python = "~=3.12.0"
pandas = "~=2.0"
pyarrow = ">=14"
polars = "~=1.17.0"
python-duckdb = "~=1.1"
duckdb-cli = "~=1.1"
matplotlib-base = "*"
seaborn-base = "~=0.13.2"
plotnine = "~=0.14.5"
notebook = ">=6.4"
seedbank = "*"
weasyprint = "*"
curl = "*"
jsonnet = "*"
pyyaml = "*"
docopt-ng = ">=0.9"
rust = ">=1.87.0,<1.88"
c-compiler = "*"
cxx-compiler = "*"
cmake = "*"
aria2 = ">=1.37.0,<2"
lenskit = "~=2025.3.0a3"
# force PyTorch to CPU-only
pytorch-cpu = "*"

# dependencies just for working with the data
[feature.data.dependencies]
libsqlite = "=3.48"
dvc = "~=3.30"
dvc-s3 = "~=3.0"
dvc-webdav = "~=3.0"

[feature.dev.dependencies]
ruff = ">=0.4"
rust-src = "~=1.73"
pre-commit = "~=4.0"
invoke = "~=2.2"
ipython = ">=8"
jupytext = "~=1.14"
parquet-tools = "*"
visidata = "*"
jupyter_console = ">=6.6.3,<7"

[feature.dev.tasks]
rerender-pipeline = "invoke rerender-pipeline"

[feature.site.dependencies]
quarto = "~=1.7"
perl = "~=5.32"

[feature.rustdoc]
channels = ["conda-forge/label/rust_dev"]
channel-priority = "disabled"

[feature.rustdoc.dependencies]
rust = { version = ">=1.74", channel = "conda-forge/label/rust_dev" }

[environments]
default = { features = ["site", "data"], solve-group = "default" }
data = { features = ["data"], no-default-feature = true, solve-group = "default" }
dev = { features = ["dev", "data", "site"], solve-group = "default" }
site = { features = ["site", "rustdoc"], no-default-feature = true }
