stages:
  scan-ratings:
    cmd: python ../run.py --rust amazon scan-ratings -o ratings.parquet ../data/az2014/ratings_Books.csv
    deps:
    - ../src/amazon.rs
    - ../src/cli/amazon/
    - ../data/az2014/ratings_Books.csv
    outs:
    - ratings.parquet

  cluster-ratings:
    cmd: python run.py --rust cluster-actions -s az-ratings -o az2014/az-cluster-ratings.parquet
    wdir: ..
    deps:
    - src/bin/cluster-actions/
    - az2014/ratings.parquet
    - book-links/all-isbns.parquet
    - book-links/isbn-clusters.parquet
    outs:
    - az2014/az-cluster-ratings.parquet
