stages:
  scan-ratings:
    cmd: python ../run.py --rust az-scan-ratings -o ratings.parquet ../data/ratings_Books.csv
    deps:
    - ../src/bin/az-scan-ratings.rs
    - ../data/ratings_Books.csv
    outs:
    - ratings.parquet

  cluster-ratings:
    cmd: python run.py --rust az-cluster-ratings -o az2014/az-cluster-ratings.parquet az2014/ratings.parquet
    wdir: ..
    deps:
    - src/bin/az-cluster-ratings.rs
    - az2014/ratings.parquet
    - book-links/all-isbns.parquet
    - book-links/isbn-clusters.parquet
    outs:
    - az2014/az-cluster-ratings.parquet
