stages:
  scan-ratings:
    cmd: python ../run.py --rust az-scan-ratings -o ratings.parquet ../data/ratings_Books.csv
    deps:
    - ../src/bin/az-scan-ratings.rs
    - ../data/ratings_Books.csv
    outs:
    - ratings.parquet

  az-cluster-ratings:
    cmd: python ../run.py --rust fusion az-cluster-ratings.tcl
    deps:
    - az-cluster-ratings.tcl
    - ratings.parquet
    - ../book-links/all-isbns.parquet
    - ../book-links/isbn-clusters.parquet
    outs:
    - az-cluster-ratings.parquet
