stages:
  scan-ratings:
    cmd: python ../run.py --rust amazon scan-ratings -o ratings.parquet ../data/az2014/ratings_Books.csv
    deps:
    - ../src/amazon.rs
    - ../src/cli/amazon/
    - ../data/az2014/ratings_Books.csv
    outs:
    - ratings.parquet

  cluster-ratings:
    cmd: python run.py --rust amazon cluster-ratings -o az2014/az-cluster-ratings.parquet az2014/ratings.parquet
    wdir: ..
    deps:
    - src/cli/amazon
    - az2014/ratings.parquet
    - book-links/isbn-clusters.parquet
    outs:
    - az2014/az-cluster-ratings.parquet

  schema:
    foreach:
    - ratings
    - az-cluster-ratings
    do:
      cmd: python ../run.py --rust pq-info -o ${item}.json ${item}.parquet
      deps:
      - ${item}.parquet
      outs:
      - ${item}.json:
          cache: false
