[LOC]
path = "../loc-mds/book-isbns.parquet"

[OL]
path = "../openlibrary/edition-isbns.parquet"

[[GR]]
path = "../goodreads/gr-book-ids.parquet"
column = "isbn10"

[[GR]]
path = "../goodreads/gr-book-ids.parquet"
column = "isbn13"

[[GR]]
path = "../goodreads/gr-book-ids.parquet"
column = "asin"

[BX]
path = "../bx/cleaned-ratings.csv"

[AZ14]
path = "../az2014/ratings.parquet"
column = "asin"
