stages:
  collect-isbns:
    cmd: python run.py --rust collect-isbns
    wdir: ..
    deps:
    - src/bin/collect-isbns.rs
    - loc-mds/book-isbns.parquet
    - openlibrary/edition-isbns.parquet
    - goodreads/gr-book-ids.parquet
    - bx/cleaned-ratings.csv
    - az2014/ratings.parquet
    outs:
    - book-links/all-isbns.parquet

  cluster:
    cmd: python run.py --rust cluster-books
    wdir: ..
    deps:
    - src/bin/cluster-books.rs
    - src/graph/
    - book-links/all-isbns.parquet
    - loc-mds/book-ids.parquet
    - loc-mds/book-isbn-ids.parquet
    - openlibrary/editions.parquet
    - openlibrary/edition-isbn-ids.parquet
    - openlibrary/all-works.parquet
    - openlibrary/edition-works.parquet
    - goodreads/gr-book-ids.parquet
    - goodreads/book-isbn-ids.parquet
    outs:
    - book-links/isbn-clusters.parquet
    - book-links/cluster-stats.parquet
    - book-links/cluster-graph-nodes.parquet
    - book-links/cluster-graph-edges.parquet
    - book-links/book-graph.mp.zst
    metrics:
    - book-links/cluster-stats.json

  cluster-ol-first-authors:
    cmd: python run.py --rust cluster-authors -o book-links/cluster-ol-first-authors.parquet
      --first-author -s openlib
    wdir: ..
    deps:
    - src/bin/cluster-authors.rs
    - book-links/isbn-clusters.parquet
    - openlibrary/edition-isbn-ids.parquet
    - openlibrary/edition-authors.parquet
    - openlibrary/author-names.parquet
    outs:
    - book-links/cluster-ol-first-authors.parquet

  cluster-loc-first-authors:
    cmd: python run.py --rust cluster-authors -o book-links/cluster-loc-first-authors.parquet
      --first-author -s loc
    wdir: ..
    deps:
    - src/bin/cluster-authors.rs
    - book-links/isbn-clusters.parquet
    - loc-mds/book-isbn-ids.parquet
    - loc-mds/book-authors.parquet
    outs:
    - book-links/cluster-loc-first-authors.parquet

  cluster-first-authors:
    cmd: python run.py --rust cluster-authors -o book-links/cluster-first-authors.parquet
      --first-author -s openlib -s loc
    wdir: ..
    deps:
    - src/bin/cluster-authors.rs
    - book-links/isbn-clusters.parquet
    - openlibrary/edition-isbn-ids.parquet
    - openlibrary/edition-authors.parquet
    - openlibrary/author-names.parquet
    - loc-mds/book-isbn-ids.parquet
    - loc-mds/book-authors.parquet
    outs:
    - book-links/cluster-first-authors.parquet

  cluster-genders:
    cmd: python run.py --rust cluster-author-gender -o book-links/cluster-genders.parquet
      -A book-links/cluster-first-authors.parquet
    wdir: ..
    deps:
    - src/bin/cluster-author-gender/
    - book-links/cluster-stats.parquet
    - book-links/cluster-first-authors.parquet
    - viaf/author-name-index.parquet
    - viaf/author-genders.parquet
    outs:
    - book-links/cluster-genders.parquet

  gender-stats:
    cmd: python ../run.py --rust fusion integration-stats.tcl
    deps:
    - integration-stats.tcl
    - cluster-genders.parquet
    - isbn-clusters.parquet
    - ../loc-mds/book-isbn-ids.parquet
    - ../bx/bx-cluster-actions.parquet
    - ../bx/bx-cluster-ratings.parquet
    - ../az2014/az-cluster-ratings.parquet
    - ../goodreads/gr-cluster-actions.parquet
    - ../goodreads/gr-cluster-ratings.parquet
    outs:
    - gender-stats.csv

  cluster-hashes:
    cmd: python ../run.py --rust cluster-hashes -o cluster-hashes.parquet
    deps:
    - ../src/bin/cluster-hashes.rs
    - isbn-clusters.parquet
    outs:
    - cluster-hashes.parquet

  debug-graph:
    cmd: python ./run.py --rust extract-graph --cluster ${debug.cluster} -o book-links/debug-graph.gml
    wdir: ..
    deps:
    - src/bin/extract-graph.rs
    - book-links/book-graph.mp.zst
    outs:
    - book-links/debug-graph.gml
