stages:
  collect-isbns:
    cmd: python run.py collect-isbns
    wdir: ..
    deps:
    - scripts/collect-isbns.py
    - loc-mds/book-isbns.parquet
    - openlibrary/edition-isbns.parquet
    - goodreads/gr-book-ids.parquet
    - bx/cleaned-ratings.csv
    - data/ratings_Books.csv
    outs:
    - book-links/all-isbns.parquet

  cluster:
    cmd: python run.py --rust cluster-books
    wdir: ..
    deps:
    - src/bin/cluster-books.rs
    - book-links/all-isbns.parquet
    - loc-mds/book-ids.parquet
    - loc-mds/book-isbn-ids.parquet
    - openlibrary/editions.parquet
    - openlibrary/edition-isbn-ids.parquet
    - openlibrary/all-works.parquet
    - openlibrary/edition-works.parquet
    - goodreads/gr-book-ids.parquet
    - goodreads/book-isbn-ids.parquet
    outs:
    - book-links/isbn-clusters.parquet
    - book-links/cluster-stats.parquet

  cluster-ol-first-authors:
    cmd: python run.py --rust cluster-authors -o book-links/cluster-ol-first-authors.parquet --first-author -s openlib
    wdir: ..
    deps:
    - src/bin/cluster-authors.rs
    - book-links/isbn-clusters.parquet
    - openlibrary/edition-isbn-ids.parquet
    - openlibrary/edition-authors.parquet
    - openlibrary/author-names.parquet
    outs:
    - book-links/cluster-ol-first-authors.parquet

  cluster-loc-first-authors:
    cmd: python run.py --rust cluster-authors -o book-links/cluster-loc-first-authors.parquet --first-author -s loc
    wdir: ..
    deps:
    - src/bin/cluster-authors.rs
    - book-links/isbn-clusters.parquet
    - loc-mds/book-isbn-ids.parquet
    - loc-mds/book-authors.parquet
    outs:
    - book-links/cluster-loc-first-authors.parquet

  cluster-first-authors:
    cmd: python run.py --rust cluster-authors -o book-links/cluster-first-authors.parquet --first-author -s openlib -s loc
    wdir: ..
    deps:
    - src/bin/cluster-authors.rs
    - book-links/isbn-clusters.parquet
    - openlibrary/edition-isbn-ids.parquet
    - openlibrary/edition-authors.parquet
    - openlibrary/author-names.parquet
    - loc-mds/book-isbn-ids.parquet
    - loc-mds/book-authors.parquet
    outs:
    - book-links/cluster-first-authors.parquet

  cluster-genders:
    cmd: python run.py --rust cluster-author-gender -o book-links/cluster-genders.parquet -A book-links/cluster-first-authors.parquet
    wdir: ..
    deps:
    - src/bin/cluster-author-gender/
    - book-links/cluster-stats.parquet
    - book-links/cluster-first-authors.parquet
    - viaf/author-name-index.parquet
    - viaf/author-genders.parquet
    outs:
    - book-links/cluster-author-genders.parquet
