stages:
  collect-isbns:
    cmd: python run.py collect-isbns
    wdir: ..
    deps:
    - scripts/collect-isbns.py
    - loc-mds/book-isbns.parquet
    - openlibrary/edition-isbns.parquet
    - goodreads/gr-book-ids.parquet
    - bx/cleaned-ratings.csv
    outs:
    - book-links/all-isbns.parquet
