stages:
  cluster:
    cmd: cargo run --release -- cluster-books --save-graph book-links/book-graph.mp.zst
    deps:
    - src/cli/cluster_books.rs
    - src/graph/
    - book-links/all-isbns.parquet
    - loc-mds/book-ids.parquet
    - loc-mds/book-isbn-ids.parquet
    - openlibrary/editions.parquet
    - openlibrary/edition-isbn-ids.parquet
    - openlibrary/all-works.parquet
    - openlibrary/edition-works.parquet
    - goodreads/gr-book-ids.parquet
    - goodreads/book-isbn-ids.parquet
    metrics:
    - book-links/cluster-metrics.json:
        cache: false
    outs:
    - book-links/book-graph.mp.zst
    - book-links/isbn-clusters.parquet
    - book-links/cluster-stats.parquet
    - book-links/cluster-graph-nodes.parquet
    - book-links/cluster-graph-edges.parquet
    wdir: ..
  cluster-first-authors:
    cmd: cargo run --release -- cluster extract-authors -o book-links/cluster-first-authors.parquet --first-author -s openlib -s loc
    deps:
    - src/cli/cluster
    - book-links/isbn-clusters.parquet
    - openlibrary/edition-isbn-ids.parquet
    - openlibrary/edition-authors.parquet
    - openlibrary/author-names.parquet
    - loc-mds/book-isbn-ids.parquet
    - loc-mds/book-authors.parquet
    outs:
    - book-links/cluster-first-authors.parquet
    wdir: ..
  cluster-genders:
    cmd: cargo run --release -- cluster extract-author-gender -o book-links/cluster-genders.parquet -A book-links/cluster-first-authors.parquet
    deps:
    - src/cli/cluster
    - book-links/cluster-stats.parquet
    - book-links/cluster-first-authors.parquet
    - viaf/author-name-index.parquet
    - viaf/author-genders.parquet
    outs:
    - book-links/cluster-genders.parquet
    wdir: ..
  cluster-hashes:
    cmd: cargo run --release -- cluster hash -o cluster-hashes.parquet isbn-clusters.parquet
    deps:
    - ../src/cli/cluster/hash.rs
    - isbn-clusters.parquet
    outs:
    - cluster-hashes.parquet
  cluster-loc-first-authors:
    cmd: cargo run --release -- cluster extract-authors -o book-links/cluster-loc-first-authors.parquet --first-author -s loc
    deps:
    - src/cli/cluster
    - book-links/isbn-clusters.parquet
    - loc-mds/book-isbn-ids.parquet
    - loc-mds/book-authors.parquet
    outs:
    - book-links/cluster-loc-first-authors.parquet
    wdir: ..
  cluster-ol-first-authors:
    cmd: cargo run --release -- cluster extract-authors -o book-links/cluster-ol-first-authors.parquet --first-author -s openlib
    deps:
    - src/cli/cluster
    - book-links/isbn-clusters.parquet
    - openlibrary/edition-isbn-ids.parquet
    - openlibrary/edition-authors.parquet
    - openlibrary/author-names.parquet
    outs:
    - book-links/cluster-ol-first-authors.parquet
    wdir: ..
  collect-isbns:
    cmd: cargo run --release -- collect-isbns -o all-isbns.parquet
    deps:
    - ../config.yaml
    - ../src/cli/collect_isbns.rs
    - ../loc-mds/book-isbns.parquet
    - ../openlibrary/edition-isbns.parquet
    - ../goodreads/gr-book-ids.parquet
    - ../az2014/ratings.parquet
    - ../az2018/ratings.parquet
    outs:
    - all-isbns.parquet
  gender-stats:
    cmd: cargo run --release -- integration-stats
    deps:
    - src/cli/stats.rs
    - book-links/cluster-genders.parquet
    - book-links/isbn-clusters.parquet
    - loc-mds/book-isbn-ids.parquet
    - az2014/az-cluster-ratings.parquet
    - az2018/az-cluster-ratings.parquet
    - goodreads/gr-cluster-actions.parquet
    - goodreads/gr-cluster-ratings.parquet
    outs:
    - book-links/gender-stats.csv
    wdir: ..
