stages:
  collect-isbns:
    cmd: python run.py collect-isbns
    wdir: ..
    deps:
    - scripts/collect-isbns.py
    - loc-mds/book-isbns.parquet
    - openlibrary/edition-isbns.parquet
    - goodreads/gr-book-ids.parquet
    - bx/cleaned-ratings.csv
    outs:
    - book-links/all-isbns.parquet

  cluster:
    cmd: python run.py cluster-books
    wdir: ..
    deps:
    - src/bin/cluster-books.rs
    - book-links/all-isbns.parquet
    - loc-mds/book-ids.parquet
    - loc-mds/book-isbn-ids.parquet
    - openlibrary/editions.parquet
    - openlibrary/edition-isbn-ids.parquet
    - openlibrary/all-works.parquet
    - openlibrary/edition-works.parquet
    - goodreads/gr-book-ids.parquet
    - goodreads/book-isbn-ids.parquet
    outs:
    - book-links/isbn-clusters.parquet
