stages:
  scan-interactions:
    cmd: python ../../run.py --rust goodreads scan interactions ../../data/goodreads/goodreads_interactions.json.gz
    deps:
    - ../../src/cli/goodreads
    - ../../src/goodreads
    - ../../data/goodreads/goodreads_interactions.json.gz
    outs:
    - gr-interactions.parquet
    - gr-users.parquet

  cluster-actions:
    cmd: python run.py --rust goodreads cluster-interactions --add-actions -o goodreads/full/gr-cluster-actions.parquet
    wdir: ../..
    deps:
    - src/cli/goodreads/cluster.rs
    - goodreads/full/gr-interactions.parquet
    - goodreads/gr-book-link.parquet
    outs:
    - goodreads/full/gr-cluster-actions.parquet

  cluster-ratings:
    cmd: python run.py --rust goodreads cluster-interactions --ratings -o goodreads/full/gr-cluster-ratings.parquet
    wdir: ../..
    deps:
    - src/cli/goodreads/cluster.rs
    - goodreads/full/gr-interactions.parquet
    - goodreads/gr-book-link.parquet
    outs:
    - goodreads/full/gr-cluster-ratings.parquet

  work-actions:
    cmd: python run.py --rust goodreads cluster-interactions --add-actions -o goodreads/full/gr-work-actions.parquet
    wdir: ../..
    deps:
    - src/cli/goodreads/cluster.rs
    - goodreads/full/gr-interactions.parquet
    - goodreads/gr-book-link.parquet
    outs:
    - goodreads/full/gr-work-actions.parquet

  work-ratings:
    cmd: python run.py --rust goodreads cluster-interactions --ratings -o goodreads/full/gr-work-ratings.parquet
    wdir: ../..
    deps:
    - src/cli/goodreads/cluster.rs
    - goodreads/full/gr-interactions.parquet
    - goodreads/gr-book-link.parquet
    outs:
    - goodreads/full/gr-work-ratings.parquet

  schema:
    foreach:
    - gr-interactions
    - gr-users
    - gr-cluster-actions
    - gr-cluster-ratings
    - gr-work-actions
    - gr-work-ratings
    do:
      cmd: python ../../run.py --rust pq-info -o ${item}.json ${item}.parquet
      deps:
      - ${item}.parquet
      outs:
      - ${item}.json:
          cache: false
