stages:
  scan-reviews:
    cmd: python ../run.py --rust amazon scan-reviews -o ratings.parquet -r reviews.parquet ../data/az2018/Books.json.gz
    deps:
    - ../src/amazon.rs
    - ../src/cli/amazon/
    - ../data/az2018/Books.json.gz
    outs:
    - ratings.parquet
    - reviews.parquet

  cluster-ratings:
    cmd: python run.py --rust cluster group-actions -s az-ratings -o az2018/az-cluster-ratings.parquet
    frozen: true
    wdir: ..
    deps:
    - src/cli/cluster/
    - az2018/ratings.parquet
    - book-links/all-isbns.parquet
    - book-links/isbn-clusters.parquet
    outs:
    - az2018/az-cluster-ratings.parquet
