stages:
  cluster-ratings:
    cmd: cargo run --release -- amazon cluster-ratings -o az2018/az-cluster-ratings.parquet az2018/ratings.parquet
    deps:
    - src/cli/amazon
    - az2018/ratings.parquet
    - book-links/isbn-clusters.parquet
    outs:
    - az2018/az-cluster-ratings.parquet
    wdir: ..
  cluster-ratings-5core:
    cmd: cargo run --release -- kcore -o az-cluster-ratings-5core.parquet az-cluster-ratings.parquet
    deps:
    - az-cluster-ratings.parquet
    - ../src/cli/kcore.rs
    outs:
    - az-cluster-ratings-5core.parquet
  scan-reviews:
    cmd: cargo run --release -- amazon scan-reviews --rating-output ratings.parquet --review-output reviews.parquet ../data/az2018/Books.json.gz
    deps:
    - ../src/amazon.rs
    - ../src/cli/amazon/
    - ../data/az2018/Books.json.gz
    outs:
    - ratings.parquet
    - reviews.parquet
