stages:
  scan-authors:
    cmd: python ../run.py --rust openlib scan-authors ../data/openlib/ol_dump_authors.txt.gz
    deps:
    - ../src/cli/openlib.rs
    - ../src/openlib/
    - ../data/openlib/ol_dump_authors.txt.gz
    outs:
    - authors.parquet
    - author-names.parquet

  scan-works:
    cmd: python ../run.py --rust openlib scan-works ../data/openlib/ol_dump_works.txt.gz
    deps:
    - ../src/cli/openlib.rs
    - ../src/openlib/
    - ../data/openlib/ol_dump_works.txt.gz
    - authors.parquet
    outs:
    - works.parquet
    - work-authors.parquet
    - work-subjects.parquet
    - author-ids-after-works.parquet

  scan-editions:
    cmd: python ../run.py --rust openlib scan-editions ../data/openlib/ol_dump_editions.txt.gz
    deps:
    - ../src/cli/openlib.rs
    - ../src/openlib/
    - ../data/openlib/ol_dump_editions.txt.gz
    - authors.parquet
    - works.parquet
    - author-ids-after-works.parquet
    outs:
    - editions.parquet
    - edition-works.parquet
    - edition-isbns.parquet
    - edition-authors.parquet
    - edition-subjects.parquet
    - all-works.parquet
    - all-authors.parquet

  edition-isbn-ids:
    cmd: python ../run.py --rust fusion edition-isbn-ids.tcl
    deps:
    - edition-isbn-ids.tcl
    - edition-isbns.parquet
    - ../book-links/all-isbns.parquet
    outs:
    - edition-isbn-ids.parquet

  schema:
    foreach:
    - authors
    - author-names
    - works
    - work-authors
    - work-subjects
    - editions
    - edition-works
    - edition-isbns
    - edition-authors
    - edition-subjects
    - all-works
    - all-authors
    - edition-isbn-ids
    do:
      cmd: python ../run.py --rust pq-info -o ${item}.json ${item}.parquet
      deps:
      - ${item}.parquet
      outs:
      - ${item}.json:
          cache: false
