stages:
  scan-authors:
    cmd: python ../run.py --rust scan-openlib -m author ../data/ol_dump_authors.txt.gz
    deps:
    - ../src/bin/scan-openlib/
    - ../data/ol_dump_authors.txt.gz
    outs:
    - authors.parquet
    - author-names.parquet

  scan-works:
    cmd: python ../run.py --rust scan-openlib -m work ../data/ol_dump_works.txt.gz
    deps:
    - ../src/bin/scan-openlib/
    - ../data/ol_dump_works.txt.gz
    - authors.parquet
    outs:
    - works.parquet
    - work-authors.parquet
