stages:
  scan-authors:
    cmd: python ../run.py --rust scan-openlib -m author ../data/ol_dump_authors.txt.gz
    deps:
    - ../data/ol_dump_authors.txt.gz
    - ../src/bin/scan-openlib/
    outs:
    - author-names.parquet
    - authors.parquet
