stages:
  author-info:
    cmd: python ../run.py sql-script author-info.sql
    deps:
    - cluster.status
    - ../index/loc-mds-book-info.status
    - ../index/loc-mds-index-books.status
    - ../index/ol-book-info.status
    - ../index/ol-index.status
    - ../index/viaf-index.status
    outs:
    - author-info.transcript

  author-stats:
    cmd: python ../run.py sql-script author-stats.sql
    deps:
    - author-stats.sql
    - author-info.status
    - ../index/az-index.status
    - ../index/bx-index.status
    - ../index/gr-index-ratings.status
    outs:
    - author-stats.transcript

  cluster:
    cmd: python ../run.py --rust cluster-graph -s cluster -T cluster.transcript
    deps:
    - ../index/gr-index-books.status
    - ../index/loc-mds-index-books.status
    - ../index/ol-index.status
    outs:
    - cluster.transcript

  cluster-stats:
    cmd: python ../run.py sql-script cluster-stats.sql
    deps:
    - cluster-stats.sql
    - cluster.status
    - ../index/gr-book-info.status
    outs:
    - cluster-stats.transcript

  status:
    foreach:
      - author-info
      - author-stats
      - cluster
      - cluster-stats
    do:
      cmd: python ../run.py stage-status -o ${item}.status ${item}
      always_changed: true
      outs:
      - ${item}.status
      deps:
      - ${item}.transcript
