stages:
  scan-books:
    cmd: python ../run.py --rust scan-marc -o loc-books.parquet --src-dir ../data/loc-books --src-prefix BooksAll.2016
    deps:
    - ../src/bin/scan-marc.rs
    - ../data/loc-books
    outs:
    - loc-books.parquet
