stages:
  scan-books:
    cmd: python ../run.py --rust scan-marc-books --glob "../data/loc-books/BooksAll.2016*.xml.gz"
    deps:
    - ../src/bin/scan-marc-books.rs
    - ../data/loc-books
    outs:
    - book-fields.parquet
    - book-ids.parquet
    - book-isbns.parquet

  book-authors:
    cmd: python ../run.py --rust fusion book-authors.tcl
    deps:
    - book-authors.tcl
    - book-fields.parquet
    outs:
    - book-authors.parquet
