cs = "http://purl.org/vocab/changeset/schema#"
identifiers = "http://id.loc.gov/vocabulary/identifiers/"
madsrdf = "http://www.loc.gov/mads/rdf/v1#"
owl = "http://www.w3.org/2002/07/owl#"
rdf = "http://www.w3.org/1999/02/22-rdf-syntax-ns#"
rdfs = "http://www.w3.org/2000/01/rdf-schema#"
rdfs1 = "http://www.w3.org/1999/02/22-rdf-schema#"
ri = "http://id.loc.gov/ontologies/RecordInfo#"
skos = "http://www.w3.org/2004/02/skos/core#"
skosxl = "http://www.w3.org/2008/05/skos-xl#"
xsd = "http://www.w3.org/2001/XMLSchema#"
names = "http://id.loc.gov/authorities/names/"
rwo = "http://id.loc.gov/rwo/"
