stages:
  book-isbn-ids:
    cmd: cargo run --release -- link-isbn-ids -o goodreads/book-isbn-ids.parquet -R book_id -I isbn10 -I isbn13 -I asin goodreads/gr-book-ids.parquet
    deps:
    - src/cli/goodreads
    - goodreads/gr-book-ids.parquet
    - book-links/all-isbns.parquet
    outs:
    - goodreads/book-isbn-ids.parquet
    wdir: ..
  book-links:
    cmd: cargo run --release -- cluster extract-books -o goodreads/gr-book-link.parquet -n book_id --join-file goodreads/gr-book-ids.parquet --join-field work_id GR-B
    deps:
    - goodreads/gr-book-ids.parquet
    - book-links/cluster-graph-nodes.parquet
    outs:
    - goodreads/gr-book-link.parquet
    wdir: ..
  cluster-actions:
    cmd: cargo run --release -- goodreads cluster-interactions --add-actions -o goodreads/gr-cluster-actions.parquet
    deps:
    - src/cli/goodreads/cluster.rs
    - goodreads/gr-book-link.parquet
    - goodreads/gr-interactions.parquet
    outs:
    - goodreads/gr-cluster-actions.parquet
    wdir: ..
  cluster-actions-5core:
    cmd: cargo run --release -- kcore -o gr-cluster-actions-5core.parquet gr-cluster-actions.parquet
    deps:
    - ../src/cli/kcore.rs
    - gr-cluster-actions.parquet
    outs:
    - gr-cluster-actions-5core.parquet
  cluster-ratings:
    cmd: cargo run --release -- goodreads cluster-interactions --ratings -o goodreads/gr-cluster-ratings.parquet
    deps:
    - src/cli/goodreads/cluster.rs
    - goodreads/gr-book-link.parquet
    - goodreads/gr-interactions.parquet
    outs:
    - goodreads/gr-cluster-ratings.parquet
    wdir: ..
  cluster-ratings-5core:
    cmd: cargo run --release -- kcore -o gr-cluster-ratings-5core.parquet gr-cluster-ratings.parquet
    deps:
    - ../src/cli/kcore.rs
    - gr-cluster-ratings.parquet
    outs:
    - gr-cluster-ratings-5core.parquet
  scan-author-info:
    cmd: cargo run --release -- goodreads scan authors ../data/goodreads/goodreads_book_authors.json.gz
    deps:
    - ../src/cli/goodreads
    - ../src/goodreads
    - ../data/goodreads/goodreads_book_authors.json.gz
    outs:
    - gr-author-info.parquet
  scan-book-genres:
    cmd: cargo run --release -- goodreads scan genres ../data/goodreads/goodreads_book_genres_initial.json.gz
    deps:
    - ../src/cli/goodreads
    - ../src/goodreads
    - ../data/goodreads/goodreads_book_genres_initial.json.gz
    outs:
    - gr-book-genres.parquet
    - gr-genres.parquet
  scan-book-info:
    cmd: cargo run --release -- goodreads scan books ../data/goodreads/goodreads_books.json.gz
    deps:
    - ../src/cli/goodreads
    - ../src/goodreads
    - ../data/goodreads/goodreads_books.json.gz
    outs:
    - gr-book-ids.parquet
    - gr-book-info.parquet
    - gr-book-authors.parquet
    - gr-book-series.parquet
  scan-interactions:
    cmd: cargo run --release -- goodreads scan interactions ../data/goodreads/goodreads_interactions.json.gz
    deps:
    - ../src/cli/goodreads
    - ../src/goodreads
    - ../data/goodreads/goodreads_interactions.json.gz
    outs:
    - gr-interactions.parquet
    - gr-users.parquet
  scan-reviews:
    cmd: cargo run --release -- goodreads scan reviews ../data/goodreads/goodreads_reviews_dedup.json.gz
    deps:
    - ../src/cli/goodreads
    - ../src/goodreads
    - ../data/goodreads/goodreads_reviews_dedup.json.gz
    - gr-book-link.parquet
    - gr-users.parquet
    outs:
    - gr-reviews.parquet
  scan-work-info:
    cmd: cargo run --release -- goodreads scan works ../data/goodreads/goodreads_book_works.json.gz
    deps:
    - ../src/cli/goodreads
    - ../src/goodreads
    - ../data/goodreads/goodreads_book_works.json.gz
    outs:
    - gr-work-info.parquet
  work-actions:
    cmd: cargo run --release -- goodreads cluster-interactions --add-actions --native-works -o goodreads/gr-work-actions.parquet
    deps:
    - src/cli/goodreads/cluster.rs
    - goodreads/gr-book-link.parquet
    - goodreads/gr-interactions.parquet
    outs:
    - goodreads/gr-work-actions.parquet
    wdir: ..
  work-actions-2015-100-10core:
    cmd: cargo run --release -- kcore --user-k 10 --item-k 100 --year 2015 -o gr-work-actions-2015-100-10core.parquet gr-work-actions.parquet
    deps:
    - gr-work-actions.parquet
    - ../src/cli/kcore.rs
    outs:
    - gr-work-actions-2015-100-10core.parquet
  work-actions-5core:
    cmd: cargo run --release -- kcore -o gr-work-actions-5core.parquet gr-work-actions.parquet
    deps:
    - ../src/cli/kcore.rs
    - gr-work-actions.parquet
    outs:
    - gr-work-actions-5core.parquet
  work-all-actions:
    cmd: python gr-work-all-actions.py
    deps:
    - gr-interactions.parquet
    - gr-book-ids.parquet
    - gr-work-all-actions.py
    outs:
    - gr-work-all-actions.parquet
  work-author:
    cmd: python gr-work-item-authors.py
    deps:
    - gr-work-item-authors.py
    - gr-book-ids.parquet
    - gr-book-authors.parquet
    - gr-author-info.parquet
    outs:
    - gr-work-item-authors.parquet
  work-gender:
    cmd: cargo run --release -- goodreads work-gender
    deps:
    - ../src/cli/goodreads
    - gr-book-link.parquet
    - ../book-links/cluster-genders.parquet
    outs:
    - gr-book-gender.parquet
    - gr-work-item-gender.parquet
  work-item-genres:
    cmd: python gr-work-item-genres.py
    deps:
    - gr-work-item-genres.py
    - gr-book-ids.parquet
    - gr-book-genres.parquet
    outs:
    - gr-work-item-genres.parquet
  work-item-titles:
    cmd: python gr-work-item-titles.py
    deps:
    - gr-work-item-titles.py
    - gr-book-ids.parquet
    - gr-book-info.parquet
    - gr-work-info.parquet
    outs:
    - gr-work-item-titles.parquet
  work-ratings:
    cmd: cargo run --release -- goodreads cluster-interactions --ratings --native-works -o goodreads/gr-work-ratings.parquet
    deps:
    - src/cli/goodreads/cluster.rs
    - goodreads/gr-book-link.parquet
    - goodreads/gr-interactions.parquet
    outs:
    - goodreads/gr-work-ratings.parquet
    wdir: ..
  work-ratings-2015-100-10core:
    cmd: cargo run --release -- kcore --user-k 10 --item-k 100 --year 2015 -o gr-work-ratings-2015-100-10core.parquet gr-work-ratings.parquet
    deps:
    - gr-work-ratings.parquet
    - ../src/cli/kcore.rs
    outs:
    - gr-work-ratings-2015-100-10core.parquet
  work-ratings-5core:
    cmd: cargo run --release -- kcore -o gr-work-ratings-5core.parquet gr-work-ratings.parquet
    deps:
    - ../src/cli/kcore.rs
    - gr-work-ratings.parquet
    outs:
    - gr-work-ratings-5core.parquet
  works-5core-dataset:
    cmd: python gr-dataset.py --works --core gr-works-5core-dataset
    deps:
    - gr-dataset.py
    - gr-work-actions-5core.parquet
    outs:
    - gr-works-5core-dataset
  works-dataset:
    cmd: python gr-dataset.py --works gr-works-dataset
    deps:
    - gr-dataset.py
    - gr-work-actions.parquet
    outs:
    - gr-works-dataset
