stages:
  scan-book-info:
    cmd: python ../run.py --rust goodreads scan books ../data/goodreads/goodreads_books.json.gz
    deps:
    - ../src/cli/goodreads
    - ../src/goodreads
    - ../data/goodreads/goodreads_books.json.gz
    outs:
    - gr-book-ids.parquet
    - gr-book-info.parquet
    - gr-book-series.parquet

  scan-work-info:
    cmd: python ../run.py --rust goodreads scan works ../data/goodreads/goodreads_book_works.json.gz
    deps:
    - ../src/cli/goodreads
    - ../src/goodreads
    - ../data/goodreads/goodreads_book_works.json.gz
    outs:
    - gr-work-info.parquet

  scan-book-genres:
    cmd: python ../run.py --rust goodreads scan genres ../data/goodreads/goodreads_book_genres_initial.json.gz
    deps:
    - ../src/cli/goodreads
    - ../src/goodreads
    - ../data/goodreads/goodreads_book_genres_initial.json.gz
    outs:
    - gr-book-genres.parquet
    - gr-genres.parquet

  book-isbn-ids:
    cmd: python ../run.py book-isbn-ids.py
    deps:
    - book-isbn-ids.py
    - gr-book-ids.parquet
    - ../book-links/all-isbns.parquet
    outs:
    - book-isbn-ids.parquet

  book-links:
    cmd: python ../run.py book-clusters.py
    deps:
    - book-clusters.py
    - gr-book-ids.parquet
    - ../book-links/cluster-graph-nodes.parquet
    outs:
    - gr-book-link.parquet

  work-gender:
    cmd: python ../run.py work-gender.py
    deps:
    - work-gender.py
    - gr-book-link.parquet
    - ../book-links/cluster-genders.parquet
    outs:
    - gr-work-gender.parquet

  schema:
    foreach:
    - gr-book-ids
    - gr-book-info
    - gr-book-link
    - gr-book-series
    - gr-book-genres
    - gr-genres
    - book-isbn-ids
    - gr-work-info
    - gr-work-gender
    do:
      cmd: python ../run.py --rust pq-info -o ${item}.json ${item}.parquet
      deps:
      - ${item}.parquet
      outs:
      - ${item}.json:
          cache: false
