stages:
  scan-book-info:
    cmd: python ../run.py --rust gr-scan-book-info ../data/goodreads_books.json.gz
    deps:
    - ../src/bin/gr-scan-book-info.rs
    - ../data/goodreads_books.json.gz
    outs:
    - gr-book-ids.parquet
    - gr-book-info.parquet

  scan-work-info:
    cmd: python ../run.py --rust gr-scan-works ../data/goodreads_book_works.json.gz
    deps:
    - ../src/bin/gr-scan-works.rs
    - ../data/goodreads_book_works.json.gz
    outs:
    - gr-work-info.parquet

  scan-interactions:
    cmd: python ../run.py --rust gr-scan-interactions ../data/goodreads_interactions.json.gz
    deps:
    - ../src/bin/gr-scan-interactions.rs
    - ../data/goodreads_interactions.json.gz
    outs:
    - gr-interactions.parquet

  book-isbn-ids:
    cmd: python ../run.py --rust fusion book-isbn-ids.tcl
    deps:
    - book-isbn-ids.tcl
    - gr-book-ids.parquet
    - ../book-links/all-isbns.parquet
    outs:
    - book-isbn-ids.parquet

  book-links:
    cmd: python ../run.py --rust gr-book-clusters
    deps:
    - ../src/bin/gr-book-clusters.rs
    - gr-book-ids.parquet
    - book-isbn-ids.parquet
    - ../book-links/isbn-clusters.parquet
    outs:
    - gr-book-link.parquet

  cluster-ratings:
    cmd: python ../run.py --rust fusion gr-cluster-ratings.tcl
    deps:
    - gr-cluster-ratings.tcl
    - gr-interactions.parquet
    - gr-book-link.parquet
    outs:
    - gr-cluster-ratings.parquet

  cluster-actions:
    cmd: python ../run.py --rust fusion gr-cluster-actions.tcl
    deps:
    - gr-cluster-actions.tcl
    - gr-interactions.parquet
    - gr-book-link.parquet
    outs:
    - gr-cluster-actions.parquet
