stages:
  scan-book-info:
    cmd: python ../run.py --rust gr-scan-book-info goodreads_books.json.gz
    deps:
    - ../src/bin/gr-scan-book-info.rs
    - goodreads_books.json.gz
    outs:
    - gr-book-ids.parquet
    - gr-book-info.parquet
  scan-interactions:
    cmd: python ../run.py --rust gr-scan-interactions goodreads_interactions.json.gz
    deps:
    - ../src/bin/gr-scan-interactions.rs
    - goodreads_interactions.json.gz
    outs:
    - gr-interactions.parquet
