stages:
  scan-book-info:
    cmd: cargo run --release -- goodreads scan books ../data/goodreads/goodreads_books.json.gz
    deps:
      - "../src/cli/goodreads"
      - "../src/goodreads"
      - "../data/goodreads/goodreads_books.json.gz"
    outs:
      - gr-book-ids.parquet
      - gr-book-info.parquet
      - gr-book-authors.parquet
      - gr-book-series.parquet
  scan-work-info:
    cmd: cargo run --release -- goodreads scan works ../data/goodreads/goodreads_book_works.json.gz
    deps:
      - "../src/cli/goodreads"
      - "../src/goodreads"
      - "../data/goodreads/goodreads_book_works.json.gz"
    outs:
      - gr-work-info.parquet
  scan-book-genres:
    cmd: cargo run --release -- goodreads scan genres ../data/goodreads/goodreads_book_genres_initial.json.gz
    deps:
      - "../src/cli/goodreads"
      - "../src/goodreads"
      - "../data/goodreads/goodreads_book_genres_initial.json.gz"
    outs:
      - gr-book-genres.parquet
      - gr-genres.parquet
  scan-author-info:
    cmd: cargo run --release -- goodreads scan authors ../data/goodreads/goodreads_book_authors.json.gz
    deps:
      - "../src/cli/goodreads"
      - "../src/goodreads"
      - "../data/goodreads/goodreads_book_authors.json.gz"
    outs:
      - gr-author-info.parquet
  book-isbn-ids:
    wdir: ".."
    cmd: cargo run --release -- link-isbn-ids -o goodreads/book-isbn-ids.parquet -R book_id -I isbn10 -I isbn13 -I asin goodreads/gr-book-ids.parquet
    deps:
      - src/cli/goodreads
      - goodreads/gr-book-ids.parquet
      - book-links/all-isbns.parquet
    outs:
      - goodreads/book-isbn-ids.parquet
  book-links:
    wdir: ".."
    cmd: cargo run --release -- cluster extract-books -o goodreads/gr-book-link.parquet -n book_id --join-file goodreads/gr-book-ids.parquet --join-field work_id GR-B
    deps:
      - goodreads/gr-book-ids.parquet
      - book-links/cluster-graph-nodes.parquet
    outs:
      - goodreads/gr-book-link.parquet
  work-gender:
    cmd: cargo run --release -- goodreads work-gender
    deps:
      - "../src/cli/goodreads"
      - gr-book-link.parquet
      - "../book-links/cluster-genders.parquet"
    outs:
      - gr-work-gender.parquet