stages:
  scan-book-info:
    cmd: python ../run.py --rust goodreads scan books ../data/goodreads/goodreads_books.json.gz
    deps:
    - ../src/cli/goodreads
    - ../src/goodreads
    - ../data/goodreads/goodreads_books.json.gz
    outs:
    - gr-book-ids.parquet
    - gr-book-info.parquet
    - gr-book-series.parquet

  scan-work-info:
    cmd: python ../run.py --rust goodreads scan works ../data/goodreads/goodreads_book_works.json.gz
    deps:
    - ../src/cli/goodreads
    - ../src/goodreads
    - ../data/goodreads/goodreads_book_works.json.gz
    outs:
    - gr-work-info.parquet

  scan-book-genres:
    cmd: python ../run.py --rust goodreads scan genres ../data/goodreads/goodreads_book_genres_initial.json.gz
    deps:
    - ../src/cli/goodreads
    - ../src/goodreads
    - ../data/goodreads/goodreads_book_genres_initial.json.gz
    outs:
    - gr-book-genres.parquet
    - gr-genres.parquet

  book-isbn-ids:
    cmd: python run.py --rust link-isbn-ids -o goodreads/book-isbn-ids.parquet -R book_id  -I isbn10 isbn13 asin -- goodreads/gr-book-ids.parquet
    wdir: ..
    deps:
    - src/cli/goodreads
    - goodreads/gr-book-ids.parquet
    - book-links/all-isbns.parquet
    outs:
    - goodreads/book-isbn-ids.parquet

  book-links:
    cmd: python run.py --rust cluster extract-books -o goodreads/gr-book-link.parquet -n book_id --join-file goodreads/gr-book-ids.parquet --join-field work_id GR-B
    wdir: ..
    deps:
    - goodreads/gr-book-ids.parquet
    - book-links/cluster-graph-nodes.parquet
    outs:
    - goodreads/gr-book-link.parquet

  work-gender:
    cmd: python ../run.py --rust goodreads work-gender
    deps:
    - ../src/cli/goodreads
    - gr-book-link.parquet
    - ../book-links/cluster-genders.parquet
    outs:
    - gr-work-gender.parquet

  schema:
    foreach:
    - gr-book-ids
    - gr-book-info
    - gr-book-link
    - gr-book-series
    - gr-book-genres
    - gr-genres
    - book-isbn-ids
    - gr-work-info
    - gr-work-gender
    do:
      cmd: python ../run.py --rust pq-info -o ${item}.json ${item}.parquet
      deps:
      - ${item}.parquet
      outs:
      - ${item}.json:
          cache: false
