stages:
  scan-interactions:
    cmd: python ../run.py --rust gr-scan-interactions goodreads_interactions.json.gz
      gr-interactions.parquet
    deps:
    - ..\src\commands\goodreads\scan_interactions.rs
    - goodreads_interactions.json.gz
    outs:
    - gr-interactions.parquet
