stages:
  scan-book-info:
    cmd: python ../run.py --rust goodreads scan books ../data/goodreads/goodreads_books.json.gz
    deps:
    - ../src/cli/goodreads.rs
    - ../src/goodreads
    - ../data/goodreads/goodreads_books.json.gz
    outs:
    - gr-book-ids.parquet
    - gr-book-info.parquet

  scan-work-info:
    cmd: python ../run.py --rust goodreads scan works ../data/goodreads/goodreads_book_works.json.gz
    deps:
    - ../src/cli/goodreads.rs
    - ../src/goodreads
    - ../data/goodreads/goodreads_book_works.json.gz
    outs:
    - gr-work-info.parquet

  scan-interactions:
    cmd: python ../run.py --rust goodreads scan interactions ../data/goodreads/goodreads_interactions.json.gz
    deps:
    - ../src/cli/goodreads.rs
    - ../src/goodreads
    - ../data/goodreads/goodreads_interactions.json.gz
    - gr-book-link.parquet
    outs:
    - gr-interactions.parquet
    - gr-users.parquet

  scan-book-genres:
    cmd: python ../run.py --rust goodreads scan genres ../data/goodreads/goodreads_book_genres_initial.json.gz
    deps:
    - ../src/cli/goodreads.rs
    - ../src/goodreads
    - ../data/goodreads/goodreads_book_genres_initial.json.gz
    outs:
    - gr-book-genres.parquet
    - gr-genres.parquet

  book-isbn-ids:
    cmd: python ../run.py book-isbn-ids.py
    deps:
    - book-isbn-ids.py
    - gr-book-ids.parquet
    - ../book-links/all-isbns.parquet
    outs:
    - book-isbn-ids.parquet

  book-links:
    cmd: python ../run.py book-clusters.py
    deps:
    - book-clusters.py
    - gr-book-ids.parquet
    - ../book-links/cluster-graph-nodes.parquet
    outs:
    - gr-book-link.parquet

  cluster-actions:
    cmd: python ../run.py gr-cluster-interactions.py --add-actions -o gr-cluster-actions.parquet
    deps:
    - gr-cluster-interactions.py
    - gr-interactions.parquet
    - gr-book-link.parquet
    outs:
    - gr-cluster-actions.parquet

  cluster-ratings:
    cmd: python ../run.py gr-cluster-interactions.py --ratings -o gr-cluster-ratings.parquet
    deps:
    - gr-cluster-interactions.py
    - gr-interactions.parquet
    - gr-book-link.parquet
    outs:
    - gr-cluster-ratings.parquet

  work-actions:
    cmd: python ../run.py gr-cluster-interactions.py --native-works --add-actions -o gr-work-actions.parquet
    deps:
    - gr-cluster-interactions.py
    - gr-interactions.parquet
    outs:
    - gr-work-actions.parquet

  work-ratings:
    cmd: python ../run.py gr-cluster-interactions.py --native-works --ratings -o gr-work-ratings.parquet
    deps:
    - gr-cluster-interactions.py
    - gr-interactions.parquet
    outs:
    - gr-work-ratings.parquet

  work-gender:
    cmd: python ../run.py work-gender.py
    deps:
    - work-gender.py
    - gr-book-link.parquet
    - ../book-links/cluster-genders.parquet
    outs:
    - gr-work-gender.parquet

  schema:
    foreach:
    - gr-book-ids
    - gr-book-info
    - gr-book-link
    - gr-book-genres
    - gr-genres
    - book-isbn-ids
    - gr-work-info
    - gr-users
    - gr-interactions
    - gr-cluster-actions
    - gr-cluster-ratings
    - gr-interactions
    - gr-work-gender
    - gr-work-actions
    - gr-work-ratings
    do:
      cmd: python ../run.py --rust pq-info -o ${item}.json ${item}.parquet
      deps:
      - ${item}.parquet
      outs:
      - ${item}.json:
          cache: false
