stages:
  author-genders:
    cmd: cargo run --release -- filter-marc --tag=375 --subfield=a --trim --lower -n gender -o author-genders.parquet viaf.parquet
    deps:
    - ../src/cli/filter_marc.rs
    - viaf.parquet
    outs:
    - author-genders.parquet
  index-names:
    cmd: cargo run --release -- index-names --marc-authorities viaf.parquet author-name-index.parquet
    deps:
    - ../src/cli/index_names.rs
    - ../src/cleaning/names
    - viaf.parquet
    outs:
    - author-name-index.parquet
    - author-name-index.csv.gz
  scan-authors:
    cmd: cargo run --release -- scan-marc -L -o viaf.parquet ../data/viaf-clusters-marc21.xml.gz
    deps:
    - ../src/cli/scan_marc.rs
    - ../src/marc
    - ../data/viaf-clusters-marc21.xml.gz
    outs:
    - viaf.parquet
