stages:
  scan-books:
    cmd: python ../run.py --rust scan-marc -L -o viaf.parquet ../data/viaf-clusters-marc21.xml.gz
    deps:
    - ../src/bin/scan-marc
    - ../data/viaf-clusters-marc21.xml.gz
    outs:
    - viaf.parquet
