stages:
  scan-authors:
    cmd: python ../run.py --rust scan-marc -L -o viaf.parquet ../data/viaf-clusters-marc21.xml.gz
    deps:
    - ../src/cli/scan_marc.rs
    - ../src/marc
    - ../data/viaf-clusters-marc21.xml.gz
    outs:
    - viaf.parquet

  author-genders:
    cmd: python ../run.py author-genders.py
    deps:
    - author-genders.py
    - viaf.parquet
    outs:
    - author-genders.parquet

  index-names:
    cmd: python ../run.py --rust index-names --marc-authorities viaf.parquet author-name-index.parquet
    deps:
    - ../src/cli/index_names.rs
    - ../src/cleaning/names
    - viaf.parquet
    outs:
    - author-name-index.parquet
    - author-name-index.csv.gz

  schema:
    foreach:
    - viaf
    - author-name-index
    - author-genders
    - author-name-index
    do:
      cmd: python ../run.py --rust pq-info -o ${item}.json ${item}.parquet
      deps:
      - ${item}.parquet
      outs:
      - ${item}.json:
          cache: false
