stages:
  scan-authors:
    cmd: python ../run.py --rust scan-marc -L -o viaf.parquet ../data/viaf-clusters-marc21.xml.gz
    deps:
    - ../src/bin/scan-marc
    - ../data/viaf-clusters-marc21.xml.gz
    outs:
    - viaf.parquet

  author-names:
    cmd: python ../run.py --rust fusion author-names.tcl
    deps:
    - author-names.tcl
    - viaf.parquet
    outs:
    - author-names.csv.gz

  author-genders:
    cmd: python ../run.py --rust fusion author-genders.tcl
    deps:
    - author-genders.tcl
    - viaf.parquet
    outs:
    - author-genders.csv.gz
