title: Book Data Tools
name: Michael Ekstrand

remote_theme: pmarsceill/just-the-docs

aux_links:
  "GitHub": https://github.com/BoiseState/bookdata-tools
  "PIReT": https://piret.info

footer_content: >
  Copyright &copy; 2020 Boise State University.  Distributed under the MIT License.
  This material is based upon work supported by the National Science Foundation under
  Grant No. IIS 17-51278. Any opinions, findings, and conclusions or recommendations
  expressed in this material are those of the author(s) and do not necessarily reflect
  the views of the National Science Foundation.
