project:
  type: book
  title: "bookdata"

keep-ipynb: true

format:
  html:
    theme: yeti
    css: tweaks.css
    mainfont: "'Inter', 'Hevetica Neue', 'Helvetica', sans-serif"

book:
  title: Book Data Tools
  author: Michael Ekstrand
  date: 2023-11-16
  chapters:
  - index.md
  - part: using/index.md
    chapters:
    - using/setup.md
    - using/storage.md
    - using/sources.md
    - using/running.md
  - part: data/index.qmd
    chapters:
    - data/ids.qmd
    - data/loc.qmd
    - data/openlib.qmd
    - data/viaf.qmd
    - data/bx.qmd
    - data/amazon.qmd
    - data/goodreads.qmd
    - data/cluster.qmd
    - data/gender.qmd
  - part: reports/index.md
    chapters:
    - reports/LinkageStats.ipynb
