project:
  type: website
  title: "bookdata"

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: tweaks.css
    toc: true

website:
  title: Book Data Tools
  repo-url: https://github.com/PIReTship/bookdata-tools
  repo-subdir: docs
  repo-actions: [edit, issue]
  sidebar:
    search: true
    contents:
    - index.md
    - section: using/index.md
      contents:
      - using/setup.md
      - using/storage.md
      - using/sources.md
      - using/running.md
    - section: data/index.qmd
      contents:
      - data/ids.qmd
      - data/loc.qmd
      - data/openlib.qmd
      - data/viaf.qmd
      - data/bx.qmd
      - data/amazon.qmd
      - data/goodreads.qmd
      - data/cluster.qmd
      - data/gender.qmd
    - section: implementation/index.md
      contents:
      - implementation/pipeline.md
      - implementation/layout.md
      - implementation/dataset.md
    - history.md
    - papers.md
    - section: reports/index.md
      contents:
      - reports/LinkageStats.ipynb
      - reports/audit-clusters.ipynb
      - reports/audit-gender-changes.ipynb
    - text: Rust API docs
      url: /apidocs/bookdata/
      icon: box-arrow-up-right
    - text: GitHub repository
      url: https://github.com/PIReTship/bookdata-tools
      icon: github
