# Environment file with minimal dependencies for building the documentation.
name: bd-docs
channels:
- conda-forge
- mdekstrand/label/depfix
- nodefaults
dependencies:
- conda-forge/label/rust_dev::rust >=1.74
- quarto
- perl
platforms:
  - linux-64
  - osx-64
  - osx-arm64
