# BookCrossing

[bx]: http://www2.informatik.uni-freiburg.de/~cziegler/BX/

The [BookCrossing data set][bx] consists of user-provided
ratings — both implicit and explicit — of books.

::: callout-note
The BookCrossing site is no longer online, so this data cannot be obtained from its
original source and the BookCrossing integration is disabled by default.  If you have
a copy of this data, save the `BX-CSV-Dump.zip` file in the `data` directory and enable
BookCrossing in `config.yaml` to use it.
:::

::: callout-important
If you use the BookCrossing data, cite:

> Cai-Nicolas Ziegler, Sean M. McNee, Joseph A. Konstan, and Georg Lausen. 2005. Improving Recommendation Lists Through Topic Diversification. <cite>Proceedings of the 14th International World Wide Web Conference</cite> (WWW '05), May 10-14, 2005, Chiba, Japan. DOI:[10.1145/1060745.1060754](https://doi.org/10.1145/1060745.1060754).
:::

Imported data lives in the `bx` directory.

## Import Steps

The import is controlled by the following DVC steps:

`data/BX-CSV-Dump.zip.dvc`
:   Download the BookCrossing zip file.

`clean-ratings`
:   Unpack ratings from the downloaded zip file and clean up their invalid characters.

`cluster-ratings`
:   Combine BookCrossing ratings with [book clusters](cluster.qmd) to produce (user, cluster, rating) from the explicit-feedback ratings. BookCrossing implicit feedback entries (rating of 0) are excluded. Produces {{< file bx/bx-cluster-ratings.parquet >}}.

`cluster-actions`
:   Combine BookCrossing interactions with [book clusters](cluster.qmd) to produce (user, cluster) implicit-feedback records. These records include the BookCrossing implicit feedback entries (rating of 0). Produces {{< file bx/bx-cluster-actions.parquet >}}.

## Raw Data {#sec-bx-raw}

The raw rating data, with invalid characters cleaned up, is in the `bx/cleaned-ratings.csv`{#file:cleaned-ratings.csv} file.
It has the following columns:

`user_id`
:   The user identifier (numeric).

`isbn`
:   The book ISBN (text).

`rating`
:   The book rating $r_{ui}$.  The ratings are on a 1-10 scale, with 0 indicating an implicit-feedback record.

## Extracted Actions {#sec-bx-extracted}

::: {.parquet file="bx/bx-cluster-ratings.parquet"}
The explicit-feedback ratings ($r_{ui} > 0$ from {{< file bx/cleaned-ratings.csv >}}), with book clusters as the `item`s.
:::

::: {.parquet file="bx/bx-cluster-actions.parquet"}
All user-item interactions from {{< file bx/cleaned-ratings.csv >}}, with book clusters as the `item`s.
:::
