# GoodReads {#sec-goodreads}

We import GoodReads data from the [UCSD Book Graph](https://mengtingwan.github.io/data/goodreads)
for additional book and user interaction information.  The source files are not automatically downloaded; you
will need the following:

- Books
- Book works
- Authors
- Book genres
- Book series
- Interaction data (the full interactions JSON file, not the summary CSV)

Download the files and save them in the `data/goodreads` directory. Each one has a corresponding `.dvc` file already in the repository.

::: callout-important
**If you use this data, cite the paper(s) documented on the data set web site.**
:::

Imported data lives in the `goodreads` directory.

## Configuration

The `config.yaml` file allows you disable the GoodReads data entirely, as well
as control whether reviews are processed:

```yaml
goodreads:
    enabled: true
    reviews: true
```

If you change the configuration, you need to [update the pipeline](../implementation/pipeline.md) before running.

## Import Steps

The import is controlled by several DVC steps:

`scan-*`
:   The various `scan-*` steps each scan a JSON file into corresponding Parquet files.  They have a specific order, as scanning interactions needs book information.

`book-isbn-ids`
:   Match GoodReads ISBNs with ISBN IDs.

`book-links`
:   Creates {{< file goodreads/gr-book-link.parquet >}}, which links each GoodReads book with its work (if applicable) and is cluster ID.

`cluster-actions`
:   Extracts cluster-level implicit feedback data.  Each (user, cluster) pair has one record, with the number of actions (the number of times the user added a book from that cluster to a shelf) and timestamp data.

`cluster-ratings`
:   Extracts cluster-level explicit feedback data.  This is the ratings each user assigned to books in each cluster.

`work-actions`, `work-ratings`
:   The same thing as the `cluster-*` stages, except it groups by GoodReads work instead of by integrated cluster. If you are only working with the GoodReads data, and not trying to connect across data sets, this data is better to work with.

`work-gender`
:   The author gender for each GoodReads work, as near as we can tell.

## Scanned and Linking Data

::: {.parquet file="goodreads/gr-book-ids.parquet"}
Identifiers extracted from each GoodReads book record.
:::


::: {.parquet file="goodreads/gr-book-info.parquet"}
Metadata extracted from GoodReads book records.
:::


::: {.parquet file="goodreads/gr-book-genres.parquet"}
GoodReads book-genre associations.
:::


::: {.parquet file="goodreads/gr-book-series.parquet"}
GoodReads book series associations.
:::


::: {.parquet file="goodreads/gr-genres.parquet"}
The genre labels to go with {{< file goodreads/gr-book-genres.parquet >}}.
:::


::: {.parquet file="goodreads/gr-book-link.parquet"}
Linking identifiers (work and cluster) for GoodReads books.
:::


::: {.parquet file="goodreads/gr-work-info.parquet"}
Metadata extracted from GoodReads work records.
:::


::: {.parquet file="goodreads/gr-interactions.parquet"}
GoodReads interaction records (from JSON).
:::


::: {.parquet file="goodreads/gr-author-info.parquet"}
GoodReads author information.
:::


## Cluster-Level Tables

These files provide action and rating data at the level of [Book Clusters](./cluster.qmd).

::: {.parquet file="goodreads/gr-cluster-actions.parquet"}
Cluster-level implicit-feedback records, suitable for use in LensKit. The `item` column contains cluster IDs.  This version of the table is processed from the JSON version of the full interaction log, which is only available by request.
:::


::: {.parquet file="goodreads/gr-cluster-ratings.parquet"}
Cluster-level explicit-feedback records, suitable for use in LensKit. The `item` column contains cluster IDs.  This version of the table is processed from the JSON version of the full interaction log, which is only available by request.
:::

## Work-Level Tables

::: {.parquet file="goodreads/gr-work-actions.parquet"}
Work-level implicit-feedback records, suitable for use in LensKit. The `item_id` column contains work IDs.
:::


::: {.parquet file="goodreads/gr-work-ratings.parquet"}
Work-level explicit-feedback records, suitable for use in LensKit. The `item_id` column contains work IDs.
:::

::: {.parquet file="goodreads/gr-work-item-gender.parquet"}
Author gender for GoodReads work-level items.  This is computed by connecting works to clusters and obtaining the cluster gender information from {{< file book-links/cluster-genders.parquet >}}.
:::

::: {.parquet file="goodreads/gr-book-gender.parquet"}
Author gender for GoodReads _books_ (not just works).  This is computed by connecting works to clusters and obtaining the cluster gender information from {{< file book-links/cluster-genders.parquet >}}.
:::
